version: "3"

services:
  app:
    env_file: .env.integration

  yarn:
    command: ""

  worker:
    env_file: .env.integration

  beat:
    env_file: .env.integration

  nginx:
    env_file: .env.integration

  firefox:
    image: b4handjr/selenium-firefox:python3-latest
    volumes:
      - .:/code
    links:
      - nginx
    expose:
      - "4444"
    ports:
      - "5900:5900"
    shm_size: 2g
    networks:
      - private_nw
      - public_nw
